Repository yesvelte/yesvelte, pull requests merged in 2023-02, with the labels that each got.

#28 #27 update and apply prettier
  .prettierrc
  src/routes/+page.svelte
  src/routes/docs/divider/+page.svelte
  src/routes/docs/el/backgrounds/+page.svelte
  src/routes/docs/el/colors/+page.svelte
  src/routes/docs/el/columns/+page.svelte
  src/routes/docs/el/columns/ColumnsOffsets.svelte
  src/routes/docs/el/grid/+page.svelte
  src/routes/docs/el/spacing/+page.svelte
  tsconfig.json
Labels: enhancement

#124 Add Dialog component
  src/css/tabler.css
  src/lib/index.js
  src/lib/modal/Modal.svelte
  src/lib/modal/Modal.types.ts
  src/lib/modal/ModalBody.svelte
  src/lib/modal/ModalFooter.svelte
  src/lib/modal/ModalHeader.svelte
  src/lib/modal/ModalTitle.svelte
  src/lib/modal/index.ts
  src/routes/docs/modal/+page.svelte
  src/routes/docs/modal/ModalAbsolute.svelte
  src/routes/docs/modal/ModalAlert.svelte
  src/routes/docs/modal/ModalBackdrop.svelte
  src/routes/docs/modal/ModalDefault.svelte
  src/routes/docs/modal/ModalDismissible.svelte
  src/routes/docs/modal/ModalHeaderMedia.svelte
  src/routes/docs/modal/ModalPersistent.svelte
  src/routes/docs/modal/ModalPlacement.svelte
  src/routes/docs/modal/ModalScrollable.svelte
  src/routes/docs/modal/ModalSize.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_modal.scss
  src/scss/tabler/components/dialog.scss
  static/css/tabler.css
  static/images/road.png
Labels: enhancement

#157 #147 rename index.js to index.ts
  src/lib/index.js
  src/lib/index.ts
Labels: enhancement

#168 #167 change `open` to `show` in Modal
  src/lib/modal/Modal.svelte
Labels: enhancement

#173 change prefix from u- to y-
  src/lib/internal/classname.ts
  src/scss/tabler/_variables.scss
  src/scss/tabler/index.scss
Labels: enhancement

#166 #161 fix stroke width of tabler icons
  src/lib/icon/Icon.svelte
Labels: enhancement

#176 #175 styles REPL issue resolved
  scripts/styles.generator.js
  src/css/tabler.css
  src/lib/css/tabler.css
Labels: bug

#169 #138 Add FileUpload component
  src/lib/file-upload/FileUpload.svelte
  src/lib/file-upload/FileUpload.types.ts
  src/lib/file-upload/index.ts
  src/lib/form/Form.types.ts
  src/lib/form/FormFileUpload.svelte
  src/lib/form/index.ts
  src/lib/index.ts
  src/routes/docs/file-upload/+page.svelte
  src/routes/docs/file-upload/FileUploadAccept.svelte
  src/routes/docs/file-upload/FileUploadDefault.svelte
  src/routes/docs/file-upload/FileUploadDisabled.svelte
  src/routes/docs/file-upload/FileUploadMultiple.svelte
  src/routes/docs/file-upload/FileUploadSizes.svelte
  src/routes/docs/file-upload/FileUploadValue.svelte
  src/routes/docs/form/form-file-upload/+page.svelte
  src/routes/docs/form/form-file-upload/FormFileUploadDefault.svelte
  src/routes/docs/form/form-file-upload/FormFileUploadHint.svelte
  src/routes/docs/form/form-file-upload/FormFileUploadLayout.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_file-upload.scss
  src/scss/tabler/components/_form-field.scss
Labels: documentation, enhancement

#165 #141 Add Steps and StepItem components
  src/lib/css/tabler.css
  src/lib/index.ts
  src/lib/steps/StepItem.svelte
  src/lib/steps/Steps.svelte
  src/lib/steps/Steps.types.ts
  src/lib/steps/index.ts
  src/routes/docs/navigations.ts
  src/routes/docs/steps/+page.svelte
  src/routes/docs/steps/StepsClick.svelte
  src/routes/docs/steps/StepsColor.svelte
  src/routes/docs/steps/StepsCounter.svelte
  src/routes/docs/steps/StepsDefault.svelte
  src/routes/docs/steps/StepsHorizontal.svelte
  src/routes/docs/steps/StepsTooltip.svelte
  src/routes/docs/steps/StepsVertical.svelte
  src/routes/docs/steps/StepsVerticalDescription.svelte
  src/routes/docs/steps/StepsWithoutTitle.svelte
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_steps.scss
  static/css/tabler.css
Labels: documentation, enhancement

#181 #180 Update navigation (sidebar menu)
  src/routes/docs/navigations.ts
Labels: bug, documentation

#184 #136 AUtocomplete & FormAutocomplete component added
  src/lib/autocomplete/Autocomplete.svelte
  src/lib/autocomplete/Autocomplete.types.ts
  src/lib/autocomplete/index.ts
  src/lib/form/Form.types.ts
  src/lib/form/FormAutocomplete.svelte
  src/lib/form/index.ts
  src/lib/index.ts
  src/routes/docs/autocomplete/+page.svelte
  src/routes/docs/autocomplete/AutocompleteDefault.svelte
  src/routes/docs/autocomplete/AutocompleteDisabled.svelte
  src/routes/docs/autocomplete/AutocompleteKey.svelte
  src/routes/docs/autocomplete/AutocompleteObject.svelte
  src/routes/docs/autocomplete/AutocompletePlaceholder.svelte
  src/routes/docs/autocomplete/AutocompleteSizes.svelte
  src/routes/docs/autocomplete/AutocompleteStates.svelte
  src/routes/docs/form/form-autocomplete/+page.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteColumn.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteDisabled.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteKey.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteLabel.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteMessage.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteObject.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompletePlaceholder.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteRequired.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteSizes.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteStates.svelte
  src/routes/docs/navigations.ts
Labels: documentation, enhancement

#185 #183 documentation css enhancement: u-* prefix changed to y-*
  src/routes/docs/autocomplete/+page.svelte
  src/routes/docs/avatar/+page.svelte
  src/routes/docs/badge/+page.svelte
  src/routes/docs/button/+page.svelte
  src/routes/docs/card/+page.svelte
  src/routes/docs/el/borders/+page.svelte
  src/routes/docs/el/spacing/+page.svelte
  src/routes/docs/input-group/+page.svelte
  src/routes/docs/input/+page.svelte
  src/routes/docs/offcanvas/+page.svelte
  src/routes/docs/progress/+page.svelte
  src/routes/docs/ribbon/+page.svelte
  src/routes/docs/select/+page.svelte
  src/routes/docs/stamp/+page.svelte
  src/routes/docs/status/+page.svelte
  src/routes/docs/textarea/+page.svelte
Labels: documentation, enhancement
