Repository yesvelte/yesvelte, pull requests merged in 2023-03, with the labels that each got.

#189 #187 fix class prop for El
  src/lib/el/El.svelte
Labels: enhancement

#192 191 define roadmap draft
  ROADMAP.md
Labels: documentation

#193 162 initial commit for table component
  ROADMAP.md
  src/lib/index.ts
  src/lib/table/Table.svelte
  src/lib/table/Table.types.ts
  src/lib/table/TableBody.svelte
  src/lib/table/TableCell.svelte
  src/lib/table/TableFoot.svelte
  src/lib/table/TableHead.svelte
  src/lib/table/TableRow.svelte
  src/lib/table/index.ts
  src/routes/docs/navigations.ts
  src/routes/docs/table/+page.svelte
  src/routes/docs/table/TableBorder.svelte
  src/routes/docs/table/TableBorderless.svelte
  src/routes/docs/table/TableColors.svelte
  src/routes/docs/table/TableDefault.svelte
  src/routes/docs/table/TableHover.svelte
  src/routes/docs/table/TableResponsive.svelte
  src/routes/docs/table/TableSort.svelte
  src/routes/docs/table/TableStriped.svelte
  src/routes/docs/table/TableTruncate.svelte
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_table.scss
Labels: documentation, enhancement

#198 #197 SCSS compilation issue resolved
  src/lib/css/tabler.css
  src/scss/tabler/components/_table.scss
  static/css/tabler.css
Labels: bug

#204 #203 Remove unused colspan prop in TableCell component
  src/lib/table/Table.types.ts
  src/lib/table/TableCell.svelte
Labels: bug

#211 54 run linter and resolve issues
  .eslintignore
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/Doc.svelte
  src/lib/breadcrumb/BreadcrumbItem.svelte
  src/lib/card/Card.types.ts
  src/lib/checkbox/Checkbox.types.ts
  src/lib/checkbox/CheckboxGroup.svelte
  src/lib/el/El.svelte
  src/lib/el/El.types.ts
  src/lib/form/Form.types.ts
  src/lib/input/Input.svelte
  src/lib/progress/ProgressBar.svelte
  src/lib/radio/Radio.svelte
  src/lib/radio/RadioGroup.svelte
  src/lib/ribbon/Ribbon.types.ts
  src/lib/select/Select.svelte
  src/lib/stamp/Stamp.svelte
  src/lib/stamp/Stamp.types.ts
  src/routes/docs/alert/AlertToggle.svelte
  src/routes/docs/card/CardTitle.svelte
  src/routes/docs/checkbox-group/CheckboxGroupLabel.svelte
  src/routes/docs/el/columns/ColumnsMargins.svelte
  src/routes/docs/form/form-checkbox-group/FormCheckboxGroupArrayBinding.svelte
  src/routes/docs/form/form-checkbox-group/FormCheckboxGroupLabel.svelte
  src/routes/docs/form/form-checkbox-group/FormCheckboxGroupLayout.svelte
  src/routes/docs/form/form-radio-group/FormRadioGroupArrayBinding.svelte
  src/routes/docs/form/form-radio-group/FormRadioGroupLabel.svelte
  src/routes/docs/label/LabelRequired.svelte
  src/routes/docs/modal/ModalScrollable.svelte
  src/routes/docs/radio-group/RadioGroupArrayBinding.svelte
  src/routes/docs/radio-group/RadioGroupLabel.svelte
  src/routes/docs/select/SelectItems.svelte
  src/routes/docs/table/TableBorderless.svelte
  src/routes/docs/table/TableColors.svelte
  src/routes/docs/table/TableSort.svelte
Labels: enhancement

#214 added array of object example
  src/routes/docs/form/form-select/+page.svelte
  src/routes/docs/form/form-select/FormSelectItemsBind.svelte
  src/routes/docs/select/+page.svelte
  src/routes/docs/select/SelectItemsBind.svelte
Labels: documentation, enhancement

#224 #223 BreadcrumbItem tag name should be `li`
  src/lib/breadcrumb/BreadcrumbItem.svelte
  src/routes/docs/breadcrumb/+page.svelte
Labels: bug, documentation

#226 #225 remove Vertical property from Slider and FormSlider
  src/lib/form/FormSlider.svelte
  src/lib/slider/Slider.svelte
  src/lib/slider/Slider.types.ts
  src/routes/docs/form/form-slider/+page.svelte
  src/routes/docs/form/form-slider/FormSliderVertical.svelte
  src/routes/docs/slider/+page.svelte
  src/routes/docs/slider/SliderVertical.svelte
  src/scss/tabler/components/_slider.scss
Labels: bug

#236 #230 add required prop for input
  src/lib/input/Input.svelte
  src/lib/input/Input.types.ts
Labels: enhancement

#242 #241 fix name prop problem of FormSelect
  src/lib/form/FormSelect.svelte
  src/lib/slider/Slider.svelte
Labels: Ready to review

#218 213 develop popup component
  ROADMAP.md
  package-lock.json
  package.json
  src/lib/css/tabler.css
  src/lib/css/tabler.min.css
  src/lib/index.ts
  src/lib/popover/Popover.svelte
  src/lib/popover/Popover.types.ts
  src/lib/popover/PopoverBody.svelte
  src/lib/popover/PopoverHeader.svelte
  src/lib/popover/index.ts
  src/lib/popup/Popup.svelte
  src/lib/popup/Popup.types.ts
  src/lib/popup/index.ts
  src/lib/tooltip/Tooltip.svelte
  src/lib/tooltip/Tooltip.types.ts
  src/lib/tooltip/index.ts
  src/routes/docs/navigations.ts
  src/routes/docs/popover/+page.svelte
  src/routes/docs/popover/PopoverComponents.svelte
  src/routes/docs/popover/PopoverDefault.svelte
  src/routes/docs/popover/PopoverDirections.svelte
  src/routes/docs/popover/PopoverHover.svelte
  src/routes/docs/tooltip/+page.svelte
  src/routes/docs/tooltip/TooltipDefault.svelte
  src/routes/docs/tooltip/TooltipHTML.svelte
  src/routes/docs/tooltip/TooltipPlacement.svelte
  src/routes/docs/tooltip/TooltipTarget.svelte
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_popover.scss
  src/scss/tabler/components/_popup.scss
  src/scss/tabler/components/_tooltip.scss
  static/css/tabler.css
  static/css/tabler.min.css
Labels: documentation, enhancement, Ready to review

#247 #246 use relative paths for imports
  src/lib/popover/Popover.types.ts
  src/lib/popup/Popup.types.ts
Labels: bug

#251 #177 add some useful props for FormInput and FormTextarea
  src/lib/form/Form.types.ts
  src/lib/form/FormInput.svelte
  src/lib/form/FormTextarea.svelte
  src/lib/input/Input.types.ts
Labels: enhancement

#254 238 add demo pages
  src/routes/demo/+layout.svelte
  src/routes/demo/+page.svelte
  src/routes/demo/authentication/forgot-password/+page.svelte
  src/routes/demo/authentication/sign-in-cover/+page.svelte
  src/routes/demo/authentication/sign-in-illustration/+page.svelte
  src/routes/demo/authentication/sign-in/+page.svelte
  src/routes/demo/authentication/sign-up/+page.svelte
  src/routes/docs/navigations.ts
  static/images/sign-in-cover.jpg
  static/images/undraw_secure_login_pdn4.svg
Labels: documentation, enhancement

#268 fix styles of range slider (tabler.min.css)
  scripts/styles.generator.js
  src/lib/slider/Slider.svelte
Labels: bug

#275 Update README.md
  README.md
Labels: documentation, enhancement

#278 #277 fix Autocomplete Complex items example
  src/lib/autocomplete/Autocomplete.svelte
  src/routes/docs/autocomplete/AutocompleteObject.svelte
Labels: bug

#279 #259 remove icon prop from Button and TabItem components
  src/lib/button/Button.svelte
  src/lib/button/Button.types.ts
  src/lib/tabs/Tab.types.ts
  src/lib/tabs/TabItem.svelte
  src/routes/docs/button-group/ButtonGroupIcon.svelte
  src/routes/docs/button/ButtonIcon.svelte
  src/routes/docs/button/ButtonSocialIcon.svelte
  src/routes/docs/tabs/TabsEnd.svelte
  src/routes/docs/tabs/TabsOnlyIcons.svelte
Labels: enhancement

#286 #285 use El for Icon component
  src/lib/icon/Icon.svelte
  src/scss/tabler/components/_icon.scss
Labels: enhancement

#282 #281 fix autocomplete bind object problem
  src/lib/autocomplete/Autocomplete.svelte
  src/routes/docs/autocomplete/+page.svelte
  src/routes/docs/autocomplete/AutocompleteEvents.svelte
  src/routes/docs/autocomplete/AutocompleteKey.svelte
  src/routes/docs/autocomplete/AutocompleteObject.svelte
Labels: documentation

#284 281 add Bind as Object example for some components
  src/lib/checkbox/CheckboxGroup.svelte
  src/routes/docs/checkbox-group/+page.svelte
  src/routes/docs/checkbox-group/CheckboxGroupBindObject.svelte
  src/routes/docs/form/form-checkbox-group/+page.svelte
  src/routes/docs/form/form-checkbox-group/FormCheckboxGroupBindObject.svelte
  src/routes/docs/form/form-radio-group/+page.svelte
  src/routes/docs/form/form-radio-group/FormRadioGroupBindObject.svelte
  src/routes/docs/form/form-select/+page.svelte
  src/routes/docs/form/form-select/FormSelectObject.svelte
  src/routes/docs/radio-group/+page.svelte
  src/routes/docs/radio-group/RadioGroupBindObject.svelte
  src/routes/docs/select/+page.svelte
  src/routes/docs/select/SelectObject.svelte
Labels: documentation

#283 #281 add option and item slot for Autocomplete
  src/lib/autocomplete/Autocomplete.svelte
  src/lib/autocomplete/Autocomplete.types.ts
  src/lib/form/FormAutocomplete.svelte
  src/routes/docs/autocomplete/+page.svelte
  src/routes/docs/autocomplete/AutocompleteAvatar.svelte
  src/routes/docs/autocomplete/AutocompleteFlags.svelte
  src/routes/docs/form/form-autocomplete/+page.svelte
  src/routes/docs/form/form-autocomplete/FormAutocompleteCustomOption.svelte
  static/images/flags/br.svg
  static/images/flags/cz.svg
  static/images/flags/de.svg
  static/images/flags/pl.svg
Labels: enhancement

#287 #132 add Dropdown component
  src/lib/dropdown/Dropdown.svelte
  src/lib/dropdown/Dropdown.types.ts
  src/lib/dropdown/DropdownItem.svelte
  src/lib/dropdown/DropdownMenu.svelte
  src/lib/dropdown/index.ts
  src/lib/index.ts
  src/routes/docs/dropdown/+page.svelte
  src/routes/docs/dropdown/DropdownAutoClose.svelte
  src/routes/docs/dropdown/DropdownDefault.svelte
  src/routes/docs/dropdown/DropdownDivider.svelte
  src/routes/docs/dropdown/DropdownEvent.svelte
  src/routes/docs/dropdown/DropdownHeader.svelte
  src/routes/docs/dropdown/DropdownHref.svelte
  src/routes/docs/dropdown/DropdownIcon.svelte
  src/routes/docs/dropdown/DropdownNoArrow.svelte
  src/routes/docs/dropdown/DropdownPlacement.svelte
  src/routes/docs/dropdown/DropdownVariants.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_dropdown.scss
Labels: documentation, enhancement

#291 289 develop sidebar component
  src/lib/index.ts
  src/lib/popup/Popup.svelte
  src/lib/popup/Popup.types.ts
  src/lib/sidebar/Sidebar.svelte
  src/lib/sidebar/Sidebar.types.ts
  src/lib/sidebar/SidebarItem.svelte
  src/lib/sidebar/index.ts
  src/routes/docs/navigations.ts
  src/routes/docs/sidebar/+page.svelte
  src/routes/docs/sidebar/SidebarActive.svelte
  src/routes/docs/sidebar/SidebarDisabled.svelte
  src/routes/docs/sidebar/SidebarHref.svelte
  src/routes/docs/sidebar/SidebarIcon.svelte
  src/routes/docs/sidebar/SidebarNested.svelte
  src/routes/docs/sidebar/SidebarSimple.svelte
  src/routes/docs/sidebar/SidebarSlots.svelte
  src/scss/tabler/_components.scss
  src/scss/tabler/_variables.scss
  src/scss/tabler/components/_sidebar.scss
Labels: documentation, enhancement

#292 269 implementing form elements page to demonstrate all form elements
  src/routes/demo/authentication/sign-in-illustration/+page.svelte
  src/routes/demo/authentication/sign-in/+page.svelte
  src/routes/demo/form-elements/+page.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/components/_el.scss
  static/images/avatars/1.jpg
  static/images/avatars/2.jpg
  static/images/avatars/3.jpg
  static/images/avatars/6.jpg
Labels: documentation
