Repository yesvelte/yesvelte, pull requests merged in 2023-04, with the labels that each got.

#296 #295 use Sidebar and SidebarItem for site layout
  src/components/Page.svelte
  src/routes/docs/navigations.ts
Labels: documentation

#308 added the sideEffects
  package.json
Labels: enhancement

#319 293 implementing sample pages
  src/routes/demo/+layout.svelte
  src/routes/demo/authentication/forgot-password/+page.svelte
  src/routes/demo/authentication/sign-in-illustration/+page.svelte
  src/routes/demo/authentication/sign-in/+page.svelte
  src/routes/demo/authentication/sign-up/+page.svelte
  src/routes/demo/faq/+page.svelte
  src/routes/demo/form-elements/+page.svelte
  src/routes/demo/pricing-cards/+page.svelte
  src/routes/demo/pricing-table/+page.svelte
  src/routes/demo/widgets/+page.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/components/_el.scss
  static/images/avatars/001f.jpg
  static/images/avatars/002f.jpg
  static/images/avatars/003f.jpg
  static/images/avatars/005f.jpg
  static/images/avatars/006f.jpg
  static/images/avatars/010m.jpg
  static/images/avatars/012f.jpg
  static/images/avatars/013f.jpg
  static/images/avatars/013m.jpg
  static/images/avatars/blond-using-her-laptop-at-her-bedroom.jpg
  static/images/avatars/book-on-the-grass.jpg
  static/images/avatars/tropical-palm-leaves-floral-pattern-background.jpg
  static/images/avatars/woman-read-book-and-drink-coffee.jpg
  static/images/food-deliver.png
  static/images/project-dashboard.png
Labels: documentation

#320 #115 update layout of docs site
  src/components/Logo.svelte
  src/components/Page.svelte
  src/components/SidebarNavigations.svelte
  src/lib/navbar/Navbar.svelte
  src/lib/navbar/Navbar.types.ts
  src/routes/docs/+layout.svelte
  src/scss/tabler/components/_navbar.scss
Labels: documentation

#323 322 add more examples for navbar component
  src/components/Page.svelte
  src/lib/navbar/Navbar.svelte
  src/lib/navbar/Navbar.types.ts
  src/routes/docs/navbar/+page.svelte
  src/routes/docs/navbar/NavbarDefault.svelte
  src/routes/docs/navbar/NavbarFullExample.svelte
  src/scss/tabler/components/_navbar.scss
Labels: documentation

#324 #315 remove margin from table
  src/scss/tabler/components/_table.scss
Labels: bug

#325 #316 fix styles of icon inside button
  src/scss/tabler/components/_button.scss
  src/scss/tabler/components/_icon.scss
Labels: bug

#327 use El in yesvelte.com/docs page
  src/components/ToC.svelte
  src/routes/docs/+layout.svelte
  src/routes/docs/+page.svelte
Labels: documentation

#332 #331 resolve issues in docs site
  src/components/Logo.svelte
  src/components/Preview.svelte
  src/routes/docs/+layout.svelte
Labels: bug, documentation

#334 #333 update sidebar navigations
  src/components/SidebarNavigations.svelte
Labels: documentation, enhancement

#335 328 fix autocomplete styles in tablermincss file
  src/lib/autocomplete/Autocomplete.svelte
  src/routes/docs/autocomplete/AutocompleteFlags.svelte
  src/scss/daisyui/components.scss
  src/scss/daisyui/components/_autocomplete.scss
  src/scss/daisyui/components/el/_text.scss
  src/scss/tabler/components/_autocomplete.scss
Labels: bug

#352 #351 fix autocomplete scroll problem
  src/routes/docs/+layout.svelte
  src/routes/docs/navbar/+page.svelte
Labels: documentation

#340 #317 fix modal alert example
  src/routes/docs/modal/ModalAlert.svelte
Labels: documentation

#368 #357 remove card from steps examples
  src/routes/docs/steps/StepsColor.svelte
  src/routes/docs/steps/StepsHorizontal.svelte
  src/routes/docs/steps/StepsVerticalDescription.svelte
Labels: documentation

#356 273 add animation in the dialog
  src/lib/accordion/AccordionBody.svelte
  src/lib/accordion/AccordionHeader.svelte
  src/lib/alert/Alert.svelte
  src/lib/el/El.svelte
  src/lib/el/El.types.ts
  src/lib/internal/animate.ts
  src/lib/internal/index.ts
  src/lib/modal/Modal.svelte
  src/lib/offcanvas/Offcanvas.svelte
  src/lib/toast/Toast.svelte
  src/scss/daisyui/components/_accordion.scss
  src/scss/daisyui/components/_alert.scss
  src/scss/daisyui/components/_modal.scss
  src/scss/tabler/components/_accordion.scss
  src/scss/tabler/components/_alert.scss
  src/scss/tabler/components/_modal.scss
  src/scss/tabler/components/_offcanvas.scss
  src/scss/tabler/components/_toast.scss
Labels: enhancement

#353 299 empty label if formswitch doesnt have label
  src/lib/form/FormSwitch.svelte
  src/lib/switch/Switch.svelte
  src/lib/switch/Switch.types.ts
Labels: enhancement

#370 358 enhance examples in documentation site
  src/components/Page.svelte
  src/routes/+layout.svelte
  src/routes/demo/+layout.svelte
  src/routes/demo/authentication/sign-in-cover/+page.svelte
  src/routes/demo/authentication/sign-in-illustration/+page.svelte
  src/routes/demo/authentication/sign-in/+page.svelte
  src/routes/demo/authentication/sign-up/+page.svelte
  src/routes/demo/form-elements/+page.svelte
  src/routes/demo/pricing-cards/+page.svelte
  src/routes/docs/navigations.ts
  src/scss/tabler/components/_popup.scss
Labels: documentation

#371 #358 fix layout problem
  src/components/Layout.svelte
  src/routes/demo/+layout.svelte
  src/routes/docs/+layout.svelte
Labels: bug

#376 #375 fix redirect problem of SidebarItem
  src/lib/sidebar/SidebarItem.svelte
Labels: bug

#381 add on:input event for Autocomplete and FormAutocomplete
  src/lib/autocomplete/Autocomplete.svelte
  src/lib/form/FormAutocomplete.svelte
  src/routes/docs/autocomplete/+page.svelte
  src/routes/docs/autocomplete/AutocompleteOnInput.svelte
Labels: enhancement

#374 #359, #369 close offcanvas after click and make scrollbar dark
  src/components/Layout.svelte
Labels: documentation

#379 add validation examples for Input component
  src/routes/docs/input/+page.svelte
  src/routes/docs/input/InputValidateOnBlur.svelte
  src/routes/docs/input/InputValidateOnType.svelte
Labels: documentation
